package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AuthResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int id;
	private java.lang.String type;
	private java.lang.String url;
	private com.rbc.db_provisioning.Related related;
	private com.rbc.db_provisioning.SummaryFields summary_fields;
	private java.lang.String created;
	private java.lang.String modified;
	private java.lang.String description;
	private int user;
	private java.lang.String token;
	private java.lang.String refresh_token;
	private java.lang.String application;
	private java.lang.String expires;
	private java.lang.String scope;

	public AuthResponse() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public java.lang.String getType() {
		return this.type;
	}

	public void setType(java.lang.String type) {
		this.type = type;
	}

	public java.lang.String getUrl() {
		return this.url;
	}

	public void setUrl(java.lang.String url) {
		this.url = url;
	}

	public com.rbc.db_provisioning.Related getRelated() {
		return this.related;
	}

	public void setRelated(com.rbc.db_provisioning.Related related) {
		this.related = related;
	}

	public com.rbc.db_provisioning.SummaryFields getSummary_fields() {
		return this.summary_fields;
	}

	public void setSummary_fields(
			com.rbc.db_provisioning.SummaryFields summary_fields) {
		this.summary_fields = summary_fields;
	}

	public java.lang.String getCreated() {
		return this.created;
	}

	public void setCreated(java.lang.String created) {
		this.created = created;
	}

	public java.lang.String getModified() {
		return this.modified;
	}

	public void setModified(java.lang.String modified) {
		this.modified = modified;
	}

	public java.lang.String getDescription() {
		return this.description;
	}

	public void setDescription(java.lang.String description) {
		this.description = description;
	}

	public int getUser() {
		return this.user;
	}

	public void setUser(int user) {
		this.user = user;
	}

	public java.lang.String getToken() {
		return this.token;
	}

	public void setToken(java.lang.String token) {
		this.token = token;
	}

	public java.lang.String getRefresh_token() {
		return this.refresh_token;
	}

	public void setRefresh_token(java.lang.String refresh_token) {
		this.refresh_token = refresh_token;
	}

	public java.lang.String getApplication() {
		return this.application;
	}

	public void setApplication(java.lang.String application) {
		this.application = application;
	}

	public java.lang.String getExpires() {
		return this.expires;
	}

	public void setExpires(java.lang.String expires) {
		this.expires = expires;
	}

	public java.lang.String getScope() {
		return this.scope;
	}

	public void setScope(java.lang.String scope) {
		this.scope = scope;
	}

	public AuthResponse(int id, java.lang.String type, java.lang.String url,
			com.rbc.db_provisioning.Related related,
			com.rbc.db_provisioning.SummaryFields summary_fields,
			java.lang.String created, java.lang.String modified,
			java.lang.String description, int user, java.lang.String token,
			java.lang.String refresh_token, java.lang.String application,
			java.lang.String expires, java.lang.String scope) {
		this.id = id;
		this.type = type;
		this.url = url;
		this.related = related;
		this.summary_fields = summary_fields;
		this.created = created;
		this.modified = modified;
		this.description = description;
		this.user = user;
		this.token = token;
		this.refresh_token = refresh_token;
		this.application = application;
		this.expires = expires;
		this.scope = scope;
	}

}