package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EraResponse implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label(value = "name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label(value = "workId")
	private java.lang.String workId;
	@org.kie.api.definition.type.Label(value = "operationId")
	private java.lang.String operationId;
	@org.kie.api.definition.type.Label(value = "dbserverId")
	private java.lang.String dbserverId;
	@org.kie.api.definition.type.Label(value = "message")
	private java.lang.String message;
	@org.kie.api.definition.type.Label(value = "entityId")
	private java.lang.String entityId;
	@org.kie.api.definition.type.Label(value = "entityName")
	private java.lang.String entityName;
	@org.kie.api.definition.type.Label(value = "entityType")
	private java.lang.String entityType;
	@org.kie.api.definition.type.Label(value = "status")
	private java.lang.String status;
	@org.kie.api.definition.type.Label(value = "associatedOperations")
	private java.lang.String associatedOperations;
	@org.kie.api.definition.type.Label(value = "dependencyReport")
	private java.lang.String dependencyReport;

	public EraResponse() {
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getWorkId() {
		return this.workId;
	}

	public void setWorkId(java.lang.String workId) {
		this.workId = workId;
	}

	public java.lang.String getOperationId() {
		return this.operationId;
	}

	public void setOperationId(java.lang.String operationId) {
		this.operationId = operationId;
	}

	public java.lang.String getDbserverId() {
		return this.dbserverId;
	}

	public void setDbserverId(java.lang.String dbserverId) {
		this.dbserverId = dbserverId;
	}

	public java.lang.String getMessage() {
		return this.message;
	}

	public void setMessage(java.lang.String message) {
		this.message = message;
	}

	public java.lang.String getEntityId() {
		return this.entityId;
	}

	public void setEntityId(java.lang.String entityId) {
		this.entityId = entityId;
	}

	public java.lang.String getEntityName() {
		return this.entityName;
	}

	public void setEntityName(java.lang.String entityName) {
		this.entityName = entityName;
	}

	public java.lang.String getEntityType() {
		return this.entityType;
	}

	public void setEntityType(java.lang.String entityType) {
		this.entityType = entityType;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public java.lang.String getAssociatedOperations() {
		return this.associatedOperations;
	}

	public void setAssociatedOperations(java.lang.String associatedOperations) {
		this.associatedOperations = associatedOperations;
	}

	public java.lang.String getDependencyReport() {
		return this.dependencyReport;
	}

	public void setDependencyReport(java.lang.String dependencyReport) {
		this.dependencyReport = dependencyReport;
	}

	public EraResponse(java.lang.String name, java.lang.String workId,
			java.lang.String operationId, java.lang.String dbserverId,
			java.lang.String message, java.lang.String entityId,
			java.lang.String entityName, java.lang.String entityType,
			java.lang.String status, java.lang.String associatedOperations,
			java.lang.String dependencyReport) {
		this.name = name;
		this.workId = workId;
		this.operationId = operationId;
		this.dbserverId = dbserverId;
		this.message = message;
		this.entityId = entityId;
		this.entityName = entityName;
		this.entityType = entityType;
		this.status = status;
		this.associatedOperations = associatedOperations;
		this.dependencyReport = dependencyReport;
	}

}