package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EraRequest implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private java.lang.String databaseType;
	private java.lang.String name;
	private java.lang.String databaseDescription;
	private java.lang.String softwareProfileId;
	private java.lang.String softwareProfileVersionId;
	private java.lang.String computeProfileId;
	private java.lang.String networkProfileId;
	private java.lang.String dbParameterProfileId;
	private com.rbc.db_provisioning.TimeMachineInfo timeMachineInfo;

	private java.util.List<com.rbc.db_provisioning.ActionArgument> actionArguments;

	private boolean createDbserver;

	private int nodeCount;

	private java.lang.String nxClusterId;

	private java.lang.String sshPublicKey;

	private boolean clustered;

	private java.util.List<com.rbc.db_provisioning.Node> nodes;

	private java.lang.String vmPassword;

	private boolean autoTuneStagingDrive;

	public EraRequest() {
	}

	public java.lang.String getDatabaseType() {
		return this.databaseType;
	}

	public void setDatabaseType(java.lang.String databaseType) {
		this.databaseType = databaseType;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getDatabaseDescription() {
		return this.databaseDescription;
	}

	public void setDatabaseDescription(java.lang.String databaseDescription) {
		this.databaseDescription = databaseDescription;
	}

	public java.lang.String getSoftwareProfileId() {
		return this.softwareProfileId;
	}

	public void setSoftwareProfileId(java.lang.String softwareProfileId) {
		this.softwareProfileId = softwareProfileId;
	}

	public java.lang.String getSoftwareProfileVersionId() {
		return this.softwareProfileVersionId;
	}

	public void setSoftwareProfileVersionId(
			java.lang.String softwareProfileVersionId) {
		this.softwareProfileVersionId = softwareProfileVersionId;
	}

	public java.lang.String getComputeProfileId() {
		return this.computeProfileId;
	}

	public void setComputeProfileId(java.lang.String computeProfileId) {
		this.computeProfileId = computeProfileId;
	}

	public java.lang.String getNetworkProfileId() {
		return this.networkProfileId;
	}

	public void setNetworkProfileId(java.lang.String networkProfileId) {
		this.networkProfileId = networkProfileId;
	}

	public java.lang.String getDbParameterProfileId() {
		return this.dbParameterProfileId;
	}

	public void setDbParameterProfileId(java.lang.String dbParameterProfileId) {
		this.dbParameterProfileId = dbParameterProfileId;
	}

	public com.rbc.db_provisioning.TimeMachineInfo getTimeMachineInfo() {
		return this.timeMachineInfo;
	}

	public void setTimeMachineInfo(
			com.rbc.db_provisioning.TimeMachineInfo timeMachineInfo) {
		this.timeMachineInfo = timeMachineInfo;
	}

	public java.util.List<com.rbc.db_provisioning.ActionArgument> getActionArguments() {
		return this.actionArguments;
	}

	public void setActionArguments(
			java.util.List<com.rbc.db_provisioning.ActionArgument> actionArguments) {
		this.actionArguments = actionArguments;
	}

	public boolean isCreateDbserver() {
		return this.createDbserver;
	}

	public void setCreateDbserver(boolean createDbserver) {
		this.createDbserver = createDbserver;
	}

	public int getNodeCount() {
		return this.nodeCount;
	}

	public void setNodeCount(int nodeCount) {
		this.nodeCount = nodeCount;
	}

	public java.lang.String getNxClusterId() {
		return this.nxClusterId;
	}

	public void setNxClusterId(java.lang.String nxClusterId) {
		this.nxClusterId = nxClusterId;
	}

	public java.lang.String getSshPublicKey() {
		return this.sshPublicKey;
	}

	public void setSshPublicKey(java.lang.String sshPublicKey) {
		this.sshPublicKey = sshPublicKey;
	}

	public boolean isClustered() {
		return this.clustered;
	}

	public void setClustered(boolean clustered) {
		this.clustered = clustered;
	}

	public java.util.List<com.rbc.db_provisioning.Node> getNodes() {
		return this.nodes;
	}

	public void setNodes(java.util.List<com.rbc.db_provisioning.Node> nodes) {
		this.nodes = nodes;
	}

	public java.lang.String getVmPassword() {
		return this.vmPassword;
	}

	public void setVmPassword(java.lang.String vmPassword) {
		this.vmPassword = vmPassword;
	}

	public boolean isAutoTuneStagingDrive() {
		return this.autoTuneStagingDrive;
	}

	public void setAutoTuneStagingDrive(boolean autoTuneStagingDrive) {
		this.autoTuneStagingDrive = autoTuneStagingDrive;
	}

	public EraRequest(
			java.lang.String databaseType,
			java.lang.String name,
			java.lang.String databaseDescription,
			java.lang.String softwareProfileId,
			java.lang.String softwareProfileVersionId,
			java.lang.String computeProfileId,
			java.lang.String networkProfileId,
			java.lang.String dbParameterProfileId,
			com.rbc.db_provisioning.TimeMachineInfo timeMachineInfo,
			java.util.List<com.rbc.db_provisioning.ActionArgument> actionArguments,
			boolean createDbserver, int nodeCount,
			java.lang.String nxClusterId, java.lang.String sshPublicKey,
			boolean clustered,
			java.util.List<com.rbc.db_provisioning.Node> nodes,
			java.lang.String vmPassword, boolean autoTuneStagingDrive) {
		this.databaseType = databaseType;
		this.name = name;
		this.databaseDescription = databaseDescription;
		this.softwareProfileId = softwareProfileId;
		this.softwareProfileVersionId = softwareProfileVersionId;
		this.computeProfileId = computeProfileId;
		this.networkProfileId = networkProfileId;
		this.dbParameterProfileId = dbParameterProfileId;
		this.timeMachineInfo = timeMachineInfo;
		this.actionArguments = actionArguments;
		this.createDbserver = createDbserver;
		this.nodeCount = nodeCount;
		this.nxClusterId = nxClusterId;
		this.sshPublicKey = sshPublicKey;
		this.clustered = clustered;
		this.nodes = nodes;
		this.vmPassword = vmPassword;
		this.autoTuneStagingDrive = autoTuneStagingDrive;
	}

}