package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MonthlySchedule implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean enabled;
	private int dayOfMonth;

	public MonthlySchedule() {
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public int getDayOfMonth() {
		return this.dayOfMonth;
	}

	public void setDayOfMonth(int dayOfMonth) {
		this.dayOfMonth = dayOfMonth;
	}

	public MonthlySchedule(boolean enabled, int dayOfMonth) {
		this.enabled = enabled;
		this.dayOfMonth = dayOfMonth;
	}

}