package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SummaryFields implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private com.rbc.db_provisioning.User user;

	public SummaryFields() {
	}

	public com.rbc.db_provisioning.User getUser() {
		return this.user;
	}

	public void setUser(com.rbc.db_provisioning.User user) {
		this.user = user;
	}

	public SummaryFields(com.rbc.db_provisioning.User user) {
		this.user = user;
	}

}