package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class User implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private int id;
	private java.lang.String username;
	private java.lang.String first_name;
	private java.lang.String last_name;

	public User() {
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public java.lang.String getUsername() {
		return this.username;
	}

	public void setUsername(java.lang.String username) {
		this.username = username;
	}

	public java.lang.String getFirst_name() {
		return this.first_name;
	}

	public void setFirst_name(java.lang.String first_name) {
		this.first_name = first_name;
	}

	public java.lang.String getLast_name() {
		return this.last_name;
	}

	public void setLast_name(java.lang.String last_name) {
		this.last_name = last_name;
	}

	public User(int id, java.lang.String username, java.lang.String first_name,
			java.lang.String last_name) {
		this.id = id;
		this.username = username;
		this.first_name = first_name;
		this.last_name = last_name;
	}

}