package com.rbc.db_provisioning;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class WeeklySchedule implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	private boolean enabled;
	private java.lang.String dayOfWeek;

	public WeeklySchedule() {
	}

	public boolean isEnabled() {
		return this.enabled;
	}

	public void setEnabled(boolean enabled) {
		this.enabled = enabled;
	}

	public java.lang.String getDayOfWeek() {
		return this.dayOfWeek;
	}

	public void setDayOfWeek(java.lang.String dayOfWeek) {
		this.dayOfWeek = dayOfWeek;
	}

	public WeeklySchedule(boolean enabled, java.lang.String dayOfWeek) {
		this.enabled = enabled;
		this.dayOfWeek = dayOfWeek;
	}

}